
package com.dasanzhone.namespace.weatherservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.dasanzhone.namespace.weatherservice.general.ForecastRequest;
import com.dasanzhone.namespace.weatherservice.general.ForecastReturn;
import com.dasanzhone.namespace.weatherservice.general.WeatherInformationReturn;
import com.dasanzhone.namespace.weatherservice.general.WeatherReturn;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WeatherService", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/")
@XmlSeeAlso({
    com.dasanzhone.namespace.weatherservice.datatypes.ObjectFactory.class,
    com.dasanzhone.namespace.weatherservice.exception.ObjectFactory.class,
    com.dasanzhone.namespace.weatherservice.general.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface WeatherService {


    /**
     * Gets Information for each WeatherID
     * 
     * @param zip
     * @return
     *     returns com.dasanzhone.namespace.weatherservice.general.WeatherInformationReturn
     * @throws WeatherException
     */
    @WebMethod(operationName = "GetWeatherInformation", action = "http://www.dasanzhone.com/namespace/weatherservice/GetWeatherInformation")
    @WebResult(name = "GetWeatherInformationResult", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
    @RequestWrapper(localName = "GetWeatherInformation", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetWeatherInformation")
    @ResponseWrapper(localName = "GetWeatherInformationResponse", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetWeatherInformationResponse")
    public WeatherInformationReturn getWeatherInformation(
        @WebParam(name = "ZIP", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
        String zip)
        throws WeatherException
    ;

    /**
     * Allows you to get your City Forecast Over the Next 7 Days, which is updated hourly.
     * 
     * @param forecastRequest
     * @return
     *     returns com.dasanzhone.namespace.weatherservice.general.ForecastReturn
     * @throws WeatherException
     */
    @WebMethod(operationName = "GetCityForecastByZIP", action = "http://www.dasanzhone.com/namespace/weatherservice/GetCityForecastByZIP")
    @WebResult(name = "GetCityForecastByZIPResult", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
    @RequestWrapper(localName = "GetCityForecastByZIP", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetCityForecastByZIP")
    @ResponseWrapper(localName = "GetCityForecastByZIPResponse", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetCityForecastByZIPResponse")
    public ForecastReturn getCityForecastByZIP(
        @WebParam(name = "ForecastRequest", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
        ForecastRequest forecastRequest)
        throws WeatherException
    ;

    /**
     * Allows you to get your City's Weather, which is updated hourly.
     * 
     * @param forecastRequest
     * @return
     *     returns com.dasanzhone.namespace.weatherservice.general.WeatherReturn
     * @throws WeatherException
     */
    @WebMethod(operationName = "GetCityWeatherByZIP", action = "http://www.dasanzhone.com/namespace/weatherservice/GetCityWeatherByZIP")
    @WebResult(name = "GetCityWeatherByZIPResult", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
    @RequestWrapper(localName = "GetCityWeatherByZIP", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetCityWeatherByZIP")
    @ResponseWrapper(localName = "GetCityWeatherByZIPResponse", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general", className = "com.dasanzhone.namespace.weatherservice.general.GetCityWeatherByZIPResponse")
    public WeatherReturn getCityWeatherByZIP(
        @WebParam(name = "ForecastRequest", targetNamespace = "http://www.dasanzhone.com/namespace/weatherservice/general")
        ForecastRequest forecastRequest)
        throws WeatherException
    ;

}
