
package com.dasanzhone.namespace.deviceservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Device", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/", wsdlLocation = "file:/D:/Develop/Java/Github/tmp/seawind/src/main/resources/service-api-definition/Device1.0.wsdl")
public class Device
    extends Service
{

    private final static URL DEVICE_WSDL_LOCATION;
    private final static WebServiceException DEVICE_EXCEPTION;
    private final static QName DEVICE_QNAME = new QName("http://www.dasanzhone.com/namespace/deviceservice/", "Device");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Develop/Java/Github/tmp/seawind/src/main/resources/service-api-definition/Device1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEVICE_WSDL_LOCATION = url;
        DEVICE_EXCEPTION = e;
    }

    public Device() {
        super(__getWsdlLocation(), DEVICE_QNAME);
    }

    public Device(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DeviceService
     */
    @WebEndpoint(name = "DeviceService")
    public DeviceService getDeviceService() {
        return super.getPort(new QName("http://www.dasanzhone.com/namespace/deviceservice/", "DeviceService"), DeviceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceService
     */
    @WebEndpoint(name = "DeviceService")
    public DeviceService getDeviceService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dasanzhone.com/namespace/deviceservice/", "DeviceService"), DeviceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEVICE_EXCEPTION!= null) {
            throw DEVICE_EXCEPTION;
        }
        return DEVICE_WSDL_LOCATION;
    }

}
